export App from './App/App'
export Home from './Home/Home'
export Widgets from './Widgets/Widgets'
export Survey from './Survey/Survey'
export About from './About/About'
export Login from './Login/Login'
export LoginSuccess from './LoginSuccess/LoginSuccess'